import express, { Request, Response } from "express";
import { computeStatsSummary } from "../services/statsEngine";
import { explainSpendingStats } from "../services/geminiService";

const router = express.Router();

/**
 * GET /api/stats/summary?month=YYYY-MM
 * Returns pre-computed spending statistics using pure MongoDB aggregations.
 */
router.get("/summary", async (req: Request, res: Response) => {
    try {
        const { month } = req.query;
        let yearNum: number;
        let monthNum: number;

        if (month) {
            const [y, m] = String(month).split("-").map(Number);
            yearNum = y;
            monthNum = m;
        } else {
            const now = new Date();
            yearNum = now.getUTCFullYear();
            monthNum = now.getUTCMonth() + 1;
        }

        if (isNaN(yearNum) || isNaN(monthNum) || monthNum < 1 || monthNum > 12) {
            return res.status(400).json({ error: "Invalid month format. Expected YYYY-MM" });
        }

        const summary = await computeStatsSummary(yearNum, monthNum);
        res.json(summary);
    } catch (error: any) {
        res.status(500).json({ error: error.message || "Failed to compute stats summary" });
    }
});

/**
 * POST /api/stats/explain
 * Accepts spending stats and returns plain-English suggestions generated by Gemini 1.5 Flash.
 */
router.post("/explain", async (req: Request, res: Response) => {
    try {
        const { month, statsSummary } = req.body;
        let summaryPayload = statsSummary;

        if (!summaryPayload) {
            let yearNum: number;
            let monthNum: number;
            if (month) {
                const [y, m] = String(month).split("-").map(Number);
                yearNum = y;
                monthNum = m;
            } else {
                const now = new Date();
                yearNum = now.getUTCFullYear();
                monthNum = now.getUTCMonth() + 1;
            }
            summaryPayload = await computeStatsSummary(yearNum, monthNum);
        }

        const advisorResult = await explainSpendingStats(summaryPayload);

        res.json({
            statsSummary: summaryPayload,
            advisorExplanation: advisorResult
        });
    } catch (error: any) {
        res.status(500).json({ error: error.message || "Failed to generate spending advice" });
    }
});

export default router;
